### ISSUE TITLE
Package installation error

### ISSUE THREAD

**Issue by somusset** [samaloney/stixpy#37]
Hi! I'm starting to test stixpy today and I hope I can be of help by providing feedback. The first feedback I have is that I did not managed to install the package...
I'm working with Windows and the github desktop so I cannot use the git command that you have in the documentation. Instead I have a copy of the package and I tried to install the package using this local copy:
```
(base) C:\Users\Sophie.Musset>pip install Documents\GitHub\stixpy\
```
and this gave me this long error message:
```
Processing c:\users\sophie.musset\documents\github\stixpy
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Sophie.Musset\Anaconda3\python.exe' 'C:\Users\Sophie.Musset\Anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\SOPHIE~1.MUS\AppData\Local\Temp\tmp2xaysl8g'
         cwd: C:\Users\Sophie.Musset\AppData\Local\Temp\pip-req-build-8ot6j04u
    Complete output (54 lines):
    C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-cs7h0l94\overlay\Lib\site-packages\setuptools\config\__init__.py:28: SetuptoolsDeprecationWarning: As setuptools moves its configuration towards `pyproject.toml`,
    `setuptools.config.read_configuration` became deprecated.

    For the time being, you can use the `setuptools.config.setupcfg` module
    to access a backward compatible API, but this module is provisional
    and might be removed in the future.

      warnings.warn(dedent(msg), SetuptoolsDeprecationWarning)
    Traceback (most recent call last):
      File "C:\Users\Sophie.Musset\Anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
        main()
      File "C:\Users\Sophie.Musset\Anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "C:\Users\Sophie.Musset\Anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-cs7h0l94\overlay\Lib\site-packages\setuptools\build_meta.py", line 188, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-cs7h0l94\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 39, in <module>
        setup(
      File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-cs7h0l94\overlay\Lib\site-packages\setuptools\__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-cs7h0l94\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 109, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-cs7h0l94\overlay\Lib\site-packages\setuptools\dist.py", line 472, in __init__
        _Distribution.__init__(
      File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-cs7h0l94\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 293, in __init__
        self.finalize_options()
      File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-cs7h0l94\overlay\Lib\site-packages\setuptools\dist.py", line 896, in finalize_options
        ep(self)
      File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-cs7h0l94\overlay\Lib\site-packages\setuptools\dist.py", line 917, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-cs7h0l94\overlay\Lib\site-packages\setuptools_scm\integration.py", line 75, in version_keyword
        _assign_version(dist, config)
      File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-cs7h0l94\overlay\Lib\site-packages\setuptools_scm\integration.py", line 48, in _assign_version
        maybe_version = _get_version(config)
      File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-cs7h0l94\overlay\Lib\site-packages\setuptools_scm\__init__.py", line 151, in _get_version
        parsed_version = _do_parse(config)
      File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-cs7h0l94\overlay\Lib\site-packages\setuptools_scm\__init__.py", line 98, in _do_parse
        version = _version_from_entrypoints(config) or _version_from_entrypoints(
      File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-cs7h0l94\overlay\Lib\site-packages\setuptools_scm\_entrypoints.py", line 37, in _version_from_entrypoints
        version: Optional[ScmVersion] = _call_entrypoint_fn(root, config, ep.load())
      File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-cs7h0l94\overlay\Lib\site-packages\setuptools_scm\_entrypoints.py", line 13, in _call_entrypoint_fn
        return fn(root, config=config)
      File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-cs7h0l94\overlay\Lib\site-packages\setuptools_scm\git.py", line 144, in parse
        wd = get_working_directory(config)
      File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-cs7h0l94\overlay\Lib\site-packages\setuptools_scm\git.py", line 129, in get_working_directory
        return GitWorkdir.from_potential_worktree(config.parent)
      File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-cs7h0l94\overlay\Lib\site-packages\setuptools_scm\git.py", line 37, in from_potential_worktree
        require_command(cls.COMMAND)
      File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-cs7h0l94\overlay\Lib\site-packages\setuptools_scm\utils.py", line 137, in require_command
        raise OSError("%r was not found" % name)
    OSError: 'git' was not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Sophie.Musset\Anaconda3\python.exe' 'C:\Users\Sophie.Musset\Anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\SOPHIE~1.MUS\AppData\Local\Temp\tmp2xaysl8g' Check the logs for full command output.
```
I have no idea what it means, I'm hopping you have some insight for me! Thank you in advance!

**Comment by hayesla** [comment]
Hey @somusset ! Hmm not too sure what's going on there, it looks like it may be a GitHub Desktop issue? Maybe @samaloney has a better solution?

Another way to test if its due to GitHub Desktop would just download the zip of the package and then do a pip install when inside the downloaded directory?

**Comment by somusset** [comment]
Hi Laura, I actually tried that too and weirdly that did not work! I'm wondering if pip is not broken on my laptop: this is what I got:
```
(base) C:\Users\Sophie.Musset>cd Documents\GitHub\stixpy\

(base) C:\Users\Sophie.Musset\Documents\GitHub\stixpy>pip install
ERROR: You must give at least one requirement to install (see "pip help install")
```

**Comment by hayesla** [comment]
can you try `pip install -e.`?

**Comment by somusset** [comment]
That helps! Apparently I cannot install without git. I copy the full error message below, it seems clear at the end that the git command is not found. Which is normal since I do not use git ^^ so I will try see how to install git on windows! 

```
(base) C:\Users\Sophie.Musset\Documents\GitHub\stixpy>pip install -e.
Obtaining file:///C:/Users/Sophie.Musset/Documents/GitHub/stixpy
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-y5els5h9\overlay\Lib\site-packages\setuptools\config\__init__.py:28: SetuptoolsDeprecationWarning: As setuptools moves its configuration towards `pyproject.toml`,
      `setuptools.config.read_configuration` became deprecated.

      For the time being, you can use the `setuptools.config.setupcfg` module
      to access a backward compatible API, but this module is provisional
      and might be removed in the future.

        warnings.warn(dedent(msg), SetuptoolsDeprecationWarning)
      Traceback (most recent call last):
        File "c:\users\sophie.musset\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "c:\users\sophie.musset\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "c:\users\sophie.musset\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-y5els5h9\overlay\Lib\site-packages\setuptools\build_meta.py", line 188, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-y5els5h9\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 39, in <module>
          setup(
        File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-y5els5h9\overlay\Lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-y5els5h9\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-y5els5h9\overlay\Lib\site-packages\setuptools\dist.py", line 472, in __init__
          _Distribution.__init__(
        File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-y5els5h9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 293, in __init__
          self.finalize_options()
        File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-y5els5h9\overlay\Lib\site-packages\setuptools\dist.py", line 896, in finalize_options
          ep(self)
        File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-y5els5h9\overlay\Lib\site-packages\setuptools\dist.py", line 917, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-y5els5h9\overlay\Lib\site-packages\setuptools_scm\integration.py", line 75, in version_keyword
          _assign_version(dist, config)
        File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-y5els5h9\overlay\Lib\site-packages\setuptools_scm\integration.py", line 48, in _assign_version
          maybe_version = _get_version(config)
        File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-y5els5h9\overlay\Lib\site-packages\setuptools_scm\__init__.py", line 151, in _get_version
          parsed_version = _do_parse(config)
        File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-y5els5h9\overlay\Lib\site-packages\setuptools_scm\__init__.py", line 98, in _do_parse
          version = _version_from_entrypoints(config) or _version_from_entrypoints(
        File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-y5els5h9\overlay\Lib\site-packages\setuptools_scm\_entrypoints.py", line 37, in _version_from_entrypoints
          version: Optional[ScmVersion] = _call_entrypoint_fn(root, config, ep.load())
        File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-y5els5h9\overlay\Lib\site-packages\setuptools_scm\_entrypoints.py", line 13, in _call_entrypoint_fn
          return fn(root, config=config)
        File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-y5els5h9\overlay\Lib\site-packages\setuptools_scm\git.py", line 144, in parse
          wd = get_working_directory(config)
        File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-y5els5h9\overlay\Lib\site-packages\setuptools_scm\git.py", line 129, in get_working_directory
          return GitWorkdir.from_potential_worktree(config.parent)
        File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-y5els5h9\overlay\Lib\site-packages\setuptools_scm\git.py", line 37, in from_potential_worktree
          require_command(cls.COMMAND)
        File "C:\Users\Sophie.Musset\AppData\Local\Temp\pip-build-env-y5els5h9\overlay\Lib\site-packages\setuptools_scm\utils.py", line 137, in require_command
          raise OSError("%r was not found" % name)
      OSError: 'git' was not found
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by hayesla** [comment]
ah ok! aw sorry I can't be more help! @samaloney may be able to assist next week :)

**Comment by samaloney** [comment]
Sorry you're having trouble. Indeed at the moment git is required to install one of the dependancies of the project - STIXCore. Until I get a release of STIXcore and stixpy up on PyPI you'll need to use have git installed. I'll try and get his sorted asap but I'm on holiday for next 1.5 weeks.

**Comment by somusset** [comment]
Hi! Thanks for the update. In the meantime I installed git and then I was able to install the package without problem and download and plot QL lightcurves perfectly fine!

**Comment by samaloney** [comment]
The dependency causing this has been removed but also `pip install stixpy` should now work.
